### ISSUE TITLE
one 7x7 conv vs. two 3x3 conv

### ISSUE THREAD

**Issue by LMMMEng** [rayleizhu/BiFormer#4]
Thank you for your wonderful work! 

It has been noted that some recent works used two 3x3 convs (stride=2) instead of one 7x7 conv (stride=4) as stem, is it because the latter can lead to better results?

**Comment by rayleizhu** [comment]
It seems that two 3x3 convs work better, according to uniformer’s choice:

https://github.com/Sense-X/UniFormer/blob/849cd0cd3b163f84102b1a799019a689d8d3fb8a/image_classification/models/uniformer.py#L341

But they do not have a strict ablation study (i.e. replacing only this patch embedding part) on this. I did not try, either, just followed their routines and focused on the attention part.






On 8 Apr 2023, at 12:58 PM, LMMMEng ***@***.***> wrote:



Thank you for your wonderful work!

It has been noted that some recent works used two 3x3 convs (stride=2) instead of one 7x7 conv (stride=4) as stem, is it because the latter can lead to better results?

**Comment by LMMMEng** [comment]
Got it, thank you!
